/**************************************
SECUENCIAS DE APROVISIONAMIENTO Y PEDIDOS
***************************************/
DROP SEQUENCE SEC_Usuarios;
DROP SEQUENCE SEC_Categorias;
DROP SEQUENCE SEC_Productos;
DROP SEQUENCE SEC_Precios;
DROP SEQUENCE SEC_Lotes;
DROP SEQUENCE SEC_Ventas;
DROP SEQUENCE SEC_LineasVenta;
DROP SEQUENCE SEC_LineasVentaEspecial;
DROP SEQUENCE SEC_ListasCompra;
DROP SEQUENCE SEC_LineasListaCompra;

/*Funciones Auxiliares*/

/**** USUARIOS (Clientes, Empleados y Encargados)*****/
CREATE SEQUENCE SEC_Usuarios;

CREATE OR REPLACE TRIGGER CREA_ID_CLIENTES
BEFORE INSERT ON Clientes
FOR EACH ROW
BEGIN
    SELECT SEC_Usuarios.NEXTVAL INTO :NEW.ID_U FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER CREA_ID_EMPLEADOS
BEFORE INSERT ON Empleados
FOR EACH ROW
BEGIN
    SELECT SEC_Usuarios.NEXTVAL INTO :NEW.ID_U FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER CREA_ID_ENCARGADOS
BEFORE INSERT ON Encargados
FOR EACH ROW
BEGIN
    SELECT SEC_Usuarios.NEXTVAL INTO :NEW.ID_U FROM DUAL;
END;
/

/****Categorias*****/
CREATE SEQUENCE SEC_Categorias;

CREATE OR REPLACE TRIGGER CREA_ID_CATEGORIA
BEFORE INSERT ON Categorias
FOR EACH ROW
BEGIN
    SELECT SEC_Categorias.NEXTVAL INTO :NEW.ID_CAT FROM DUAL;
END;
/

/****PRODUCTOS*****/
CREATE SEQUENCE SEC_Productos;

CREATE OR REPLACE TRIGGER CREA_ID_PRODUCTO
BEFORE INSERT ON Productos
FOR EACH ROW
BEGIN
    SELECT SEC_Productos.NEXTVAL INTO :NEW.ID_PRO FROM DUAL;
END;
/

/****Precios*****/

CREATE SEQUENCE SEC_Precios;

CREATE OR REPLACE TRIGGER CREA_ID_PRECIOS
BEFORE INSERT ON Precios
FOR EACH ROW
BEGIN
    SELECT SEC_Precios.NEXTVAL INTO :NEW.ID_PRE FROM DUAL;
END;
/

/****Lotes*****/
CREATE SEQUENCE SEC_Lotes;

CREATE OR REPLACE TRIGGER CREA_ID_LOTES
BEFORE INSERT ON Lotes
FOR EACH ROW
BEGIN
    SELECT SEC_Lotes.NEXTVAL INTO :NEW.ID_L FROM DUAL;
END;
/

/****Ventas*****/
CREATE SEQUENCE SEC_Ventas;

CREATE OR REPLACE TRIGGER CREA_ID_VENTAS
BEFORE INSERT ON Ventas
FOR EACH ROW
BEGIN
    SELECT SEC_Ventas.NEXTVAL INTO :NEW.ID_V FROM DUAL;
END;
/

/****LineasVenta*****/
CREATE SEQUENCE SEC_LineasVenta;

CREATE OR REPLACE TRIGGER CREA_ID_LINEASVENTA
BEFORE INSERT ON LineasVenta
FOR EACH ROW
BEGIN
    SELECT SEC_LineasVenta.NEXTVAL INTO :NEW.ID_lV FROM DUAL;
END;
/

/****LineasVentaEspacial*****/
CREATE SEQUENCE SEC_LineasVentaEspecial;

CREATE OR REPLACE TRIGGER CREA_ID_LINEASVENTAESPECIAL
BEFORE INSERT ON LineasVentaEspecial
FOR EACH ROW
BEGIN
    SELECT SEC_LineasVentaEspecial.NEXTVAL INTO :NEW.ID_lVE FROM DUAL;
END;
/

/****Listas Compra*****/
CREATE SEQUENCE SEC_ListasCompra;

CREATE OR REPLACE TRIGGER CREA_ID_LISTASCOMPRA
BEFORE INSERT ON ListasCompra
FOR EACH ROW
BEGIN
    SELECT SEC_ListasCompra.NEXTVAL INTO :NEW.ID_LC FROM DUAL;
END;
/
/****Lineas ListaCompra*****/
CREATE SEQUENCE SEC_LineasListaCompra;

CREATE OR REPLACE TRIGGER CREA_ID_LINEASLISTACOMPRA
BEFORE INSERT ON LineasListaCompra
FOR EACH ROW
BEGIN
    SELECT SEC_LineasListaCompra.NEXTVAL INTO :NEW.ID_LLC FROM DUAL;
END;
/